### PR TITLE
Container interop

### PR DESCRIPTION
**Pull request by abdala**
Reference to issue #53

### CODE REVIEW

**Comment by leoqbc** [comment]
Nice work @abdala! I think it's a great start for the Container Interp. implementetion, what do you think @alganet?

**Comment by augustohp** [comment]
I am a :+1:, I would just *rebase* and *squash* both commits into one.

**Comment by leoqbc** [comment]
Awesome I'm a :+1: too!

**Comment by abdala** [comment]
Rebased. :)

**Comment by henriquemoody** [comment]
Thanks for contributing, @abdala!

:panda_face:

**Pull request merged**
